### ISSUE TITLE
xThemes no se instala correctamente

### ISSUE THREAD

**Issue by ryuaka** [redmexico/xthemes#1]
![issue 1](https://cloud.githubusercontent.com/assets/13698936/9144076/1ba37650-3d10-11e5-92e8-067c410795e8.jpg)
![issue 2](https://cloud.githubusercontent.com/assets/13698936/9144077/1bb478f6-3d10-11e5-85b5-0adfb40ff1df.jpg)

He estado tratando de instalar xThemes en cualquier versión que tienes publicada aquí mismo, pero a pesar de que se instala se corrompen varias cosas. La primera es que al instalarse y después regresar al panel de control de RMCommon, este se muestra sin formato, aparece un fondo blanco y las opciones se muestran en forma de lista. Lo segundo es que no se puede entrar al módulo, al intentarlo aparece en blanco todo.

Lo raro es que no da errores. Por otro lado, he probado cambiando la versión de PHP por que al principio usaba la 5.6, después lo intenté con la 5.5 y siguió dando problemas y al final puse la 5.4, y al principio aparentemente todo estaba bien, me dejó inclusive instalar un tema basado en xTthemes, pero al intentar de agregar un menú por ejemplo, me siguió dando este mismo problema.

He intentado usar las versiones de Common Utilities 2.2.8.2 y la versión 2.2.9.6, y ambas funcionan bien, pero al parecer xThemes es quien da problemas. Usé desde la 1.6.1.9 hasta la versión 1.6.2.5 dando todas el mismo problema. 

Por otro lado, he instalado AdvForms como es debido, pero igual el problema se presenta. También cabe señalar que el programa si se registra en ...xoops_cache/xoops_system_modules_active.php.

Un saludo Eduardo.

**Comment by bitcero** [comment]
Solucionado: el error estaba relacionado con el tema y sus requerimientos.
