### ISSUE TITLE
Fatal error: Class 'XtAssembler'

### ISSUE THREAD

**Issue by Pentasma** [redmexico/xthemes#10]
XOOPS: 2.5.8 
PHP: 5.6.20
MYSQL: 5.6.33

Rmcommon-master.zip / Common Utilities 2.3.4.1 was downloaded today and installed on fresh xoops 2.5.8 site with pm, profile & protector already installed. 

Now i went ahead and installed all of your modules. In which I have a fatal error below & another Unknown when entering the admin section. I went ahead and posted the Notice as well that was with this fatal (Sorry to be redundant) See below...

---

Fatal error: Class 'XtAssembler' not found in /home/fastnaught/public_html/modules/xthemes/events/rmcommon.php on line 21
None All Errors (2) Deprecated (0) Queries (34) Blocks (0) Extra (2) Timers(3)

Errors
Unknown: call_user_func_array() expects parameter 1 to be a valid callback, non-static method QpagesRmcommonPreload::eventRmcommonRegisterIconProvider() should not be called statically in file /modules/rmcommon/api/events.php line 122

Notice: You must provide the caption and value when add a new cell to Counter Widget in file /modules/rmcommon/widgets/Counter.php line 133

Thanks
Ace

**Comment by bitcero** [comment]
To solve the "Fatal Error" in xThemes you need to check if the module was added to active modules array (this is a problem with Xoops). To do this please use a text editor (code editor) and open the file `xoops_data/caches/xoops_cache/xoops_[...]_system_modules_active.php`.

You will see something like this:

``` php
return array (
  0 => 'system',
  1 => 'rmcommon',
);
```

add xthemes to this array:

``` php
return array (
  0 => 'system',
  1 => 'rmcommon',
  2 => 'xthemes',
);
```

save file and reload page.

**Comment by Pentasma** [comment]
That worked perfect Eduardo thank you! The site is back up and running. 
Should all your modules be added to system_modules_active.php? 

## This is what i have now...

return array (
  0 => 'system',
  1 => 'pm',
  2 => 'profile',
  3 => 'protector',
  4 => 'rmcommon',
  5 => 'bxpress',
  6 => 'xthemes',
);

However I have these installed as well.
mywords
qpages
works

Should those be in the file as well?

**Comment by bitcero** [comment]
Yes. The true is that installer must to add automatically during install process, but sometimes XOOPS does not update the file (_I don't know why_). However, to prevent errors, add the modules to the file.

**Comment by Pentasma** [comment]
IDK either, maybe issues with xoops_data being outside of public_html as public is  chmod 750 on Apache. Thanks again Eduardo
