### ISSUE TITLE
No se pueden mover los menús creados

### ISSUE THREAD

**Issue by ryuaka** [redmexico/xthemes#4]
No es posible mover los menús para organizarlos y hacer niveles de menús, o acomodarlos hacia arriba o hacia abajo. Por alguna razón no se mueven.

He verificado el debugger pero no aparece nada que haga referencia a eso. También he hecho pruebas tanto en local como en servidor web y en ambos casos es lo mismo, no se pueden mover los menús hechos con xThemes.

Estoy manejando lo siguiente:

PHP: 5.6
XOOPS: 2.5.7.2
Common Utilities: 2.3.1.9

**Comment by bitcero** [comment]
¿Que versión de xThemes utilizas?

¿Puedes verificar en la consola de javascript de tu navegador si existe algún error? Este error podría deberse a algún conflicto con algún otro script. No he podido reproducirlo, así que hace falta investigar un poco mas.

**Comment by ryuaka** [comment]
Me marca lo siguiente en jquery.nestedSortable.min.js:

> Uncaught TypeError: Cannot read property 'sortable' of undefined - jquery.nestedSortable.min.js:1

La versión de xThemes que ando manejando es la 1.6.3.5

**Encontré la fuente del error**. Sucede que en las opciones de Common Utilities de la nueva versión 2.3.1.9 la opción de **"Activar jQuery para los temas"** viene desactivada por default; solo activé esa opción y los menús han funcionado nuevamente.

**Comment by bitcero** [comment]
Perfecto! Gracias por reportar... cierro el hilo.
