### ISSUE TITLE
Pagina en blanco despues de instalar y entrar a temas

### ISSUE THREAD

**Issue by markosc** [redmexico/xthemes#6]
Cuando ingreso, instalo xthemes, y voy a tablero o temas, sale error... y toda la web se desencadena con ese error, elimino la carpeta y vuelve a la normalidad....
XOOPS: 2.5.8
PHP: 5.6.22
MYSQL: 5.5.45
Common Utilities: 2.3.2.8

**Comment by bitcero** [comment]
Verifica que xThemes se encuentre agregado en el archivo de módulos activos.

Abre el archivo `xoops_cache/xoops_[···]_system_modules_active.php` y verifica que exista una línea para xthemes. Si no es así tan solo añádela y debería funcionar.

**Comment by markosc** [comment]
gracias, funciona bien solo que no se ven los demás temas y solo  el tema seleccionado.

**Comment by bitcero** [comment]
ok... déjame revisar.

**Comment by markosc** [comment]
Unknown: call_user_func() expects parameter 1 to be a valid callback, non-static method XthemesCorePreload::eventCoreIncludeCommonLanguage() should not be called statically in file /class/preload.php line 139
Unknown: Declaration of XtTheme::errors() should be compatible with RMObject::errors($html = true) in file /modules/xthemes/class/xttheme.php line 15
Unknown: Static function RMIPlugin::getInstance() should not be abstract in file /modules/rmcommon/class/iplugin.php line 73

**Comment by bitcero** [comment]
Por favor descarga los archivos de la rama "master"  y dime si presenta el mismo error.

**Comment by markosc** [comment]
si el mismo pero no solo eso ahora no puedo ir a la configuración del tema, es decir no puedo acceder al panel de bloques y seleccion de categoria que el theme ofrecia.

**Comment by bitcero** [comment]
Puedes postear el registro de errores de Xoops? Deberías poder ver algo como en la imagen siguiente:
![xthemes](https://cloud.githubusercontent.com/assets/1305172/16179658/635e1606-3631-11e6-85bf-622d8fe3b1a0.jpg)

**Comment by markosc** [comment]
![Uploading imagen.jpg…]()
ok 
................../modules/xthemes/themes.php
Unknown: Static function RMIPlugin::getInstance() should not be abstract in file /modules/rmcommon/class/iplugin.php line 73
Unknown: call_user_func_array() expects parameter 1 to be a valid callback, non-static method QpagesRmcommonPreload::eventRmcommonLoadRightWidgets() should not be called statically in file /modules/rmcommon/api/events.php line 122

................../modules/xthemes/theme.php
Unknown: El método RMTemplate::add_theme_style está obsoleto. En su lugar utiliza RMTemplate::add_style(). in file /modules/rmcommon/class/template.php line 1490
Unknown: Static function RMIPlugin::getInstance() should not be abstract in file /modules/rmcommon/class/iplugin.php line 73
Unknown: call_user_func_array() expects parameter 1 to be a valid callback, non-static method QpagesRmcommonPreload::eventRmcommonLoadRightWidgets() should not be called statically in file /modules/rmcommon/api/events.php line 122

**Comment by markosc** [comment]
fui a configuración (del sistema, no de rmcommon) y escogí un tema por defecto, volvi al módulo xthemes, y volvi a "instalar" y todo ok, gracias.

**Comment by bitcero** [comment]
Extraño... pero que bien que funcione. Seguiré pendiente por si vuelve a suceder. Cierro el hilo. Saludos.
